---
- name: Install prerequisites
  package:
    name: "{{ lgsm_required_packages }}"
    state: present

- name: Setup admin group
  group:
    name: "{{ lgsm_group }}"
    state: present

- name: Setup admin user
  user:
    name: "{{ lgsm_user }}"
    group: "{{ lgsm_group }}"
    groups: "{{ lgsm_additional_groups }}"
    comment: "{{ lgsm_comment }}"
    system: yes
    home: "{{ lgsm_installdir }}"
    state: present

- name: Download lgsm installer
  get_url:
    url: "{{ lgsm_installer_url }}"
    dest: "{{ lgsm_installdir }}/{{ lgsm_installer_name }}"
    owner: "{{ lgsm_user }}"
    group: "{{ lgsm_group }}"
    mode: '0755'
